name: Docker image push
on:
  push:
    branches:
      - docker

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Login to Dokcer Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        id: build-and-push
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: webispy/checkpatch
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.repository.default_branch }}
      - name: Update Dockerfile in default branch with digest
        run: sed -ri 's#(FROM webispy/checkpatch@).*#\1${{ steps.build-and-push.outputs.digest }}#' Dockerfile
      - name: Create Pull Request with updated Dockerfile
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Roll Dockerfile digest
          base: ${{ github.event.repository.default_branch }}
